### ISSUE TITLE
Running locally this action

### ISSUE THREAD

**Issue by dinko-pehar** [crystal-ameba/github-action#12]
From the README.md:

Build the docker image:

> docker build . -t crystal-ameba/github-action
Run it:

> docker run -it crystal-ameba/github-action

But it fails with stack trace:
```
Unhandled exception: Missing ENV key: "GITHUB_WORKSPACE" (KeyError)
  from /usr/share/crystal/src/env.cr:53:7 in 'fetch'
  from /usr/share/crystal/src/env.cr:22:5 in '[]'
  from src/ameba-github_action/runner.cr:8:20 in 'initialize'
  from src/ameba-github_action/runner.cr:7:5 in 'new'
  from src/ameba-github_action.cr:4:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:110:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:96:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:119:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

Any way to run this locally ? I'm contributing to closed source project written in Crystal and using this action in GitHub on pull request, it passed the checks while running ameba locally as dependency, it failed (on purpose introduced fail):
```

[W] Lint/UselessAssign: Useless assignment to variable `p`
> p = 3
  ^

Finished in 8.93 seconds
30 inspected, 1 failure
```

EDIT:

Also, this is ameba jobs in our workflow:

```
# AMEBA
  ameba-test:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Crystal Ameba Linter
        id: crystal-ameba
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
